[package]
name = "archi-view-importer"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "^4.2.0"
encoding_rs = "0.8.35"
uuid = { version = "1.17.0", features = ["v4"] }
xot = "0.31.0"
clap = { version = "4.5.40", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8.0"